### ISSUE TITLE
[Bug] Files dissapear from file list when sorting by mod. date and view sub-folders

### ISSUE THREAD

**Issue by neurosock** [ozntel/file-tree-alternative#144]
Dear [ozntel](https://github.com/ozntel) 

I would like to reopen #88. The issue still persists as the newest version (2.3.3) but seems to require certain things to be enabled for it to happen. I have here a list of steps that may help reproduce it on your side:
OS: Windows 10
Obsidian: 1.1.16
Installer: 0.15.9
Plugin: 2.3.3

- Create new vault
- Install plugin
- With default settings, in the file panel set "Show files from sub-folders" and "Sort by last update"
- Create the following file structure
```
    folder0
        test3.md
        test4.md
    folder1
        test5.md
        test6.md
    test0.md
    test1.md
    test2.md
```
- Modify any files from the root folder, no problem observed
- Modify any files from the sub-folders, sub-folder files disappear from the file list

Here a short gif of the effect. You can see how test6.md and test5.md disappear from the list (after a small delay, I suspect this is the Obsidian auto-save trigger)
![FTABug0](https://user-images.githubusercontent.com/76121344/226563144-0381c2ae-bad3-4148-b145-df06eaeca959.gif)

Thanks for your awesome work!

**Comment by lifepix** [comment]
I'm also experiencing this problem on Mac. 

It doesn't seem to happen when editing a subfolder item with only the subfolder items displayed in the file pane. But it does occur when editing subfolder items in the root folder level view.

OS: Mac Ventura 13.5.2
Obsidian: 1.4.13 (Installer 1.4.13)
Plugin: 2.3.6

**Comment by ozntel** [comment]
Can you try if it works after the latest release? It should be fixed now

**Comment by lifepix** [comment]
Sorry @ozntel, it's still not fixed when I just tested it. Same issue with edited note disappearing from the root folder level view. 

OS: Mac Ventura 13.6.1
Obsidian: 1.4.16 (Installer 1.4.13)
Plugin: 2.3.9

**Comment by lifepix** [comment]
> Ok it looks like i fixed all other folders except for the root folder since it's path is not purely "" but "/" and the logic was not able to identify if the file update rolls up to the root folder. Now hopefully it should be fixed. Can you validate?

Yes, it's fixed now. Thanks a lot for this. It's working nicely now and no more navigating away from the root and then back in to refresh the list. Appreciate all your work on the plugin.
